# Generated by Django 4.0.3 on 2022-09-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezikr', '0003_task_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='script',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
