# Generated by Django 4.0.3 on 2022-09-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezikr', '0004_alter_task_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ztype',
        ),
        migrations.AddField(
            model_name='task',
            name='ztype',
            field=models.ManyToManyField(blank=True, null=True, to='ezikr.ztype'),
        ),
    ]
