# Generated by Django 4.0.3 on 2022-09-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezikr', '0005_remove_task_ztype_task_ztype'),
    ]

    operations = [
        migrations.AddField(
            model_name='challange',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
