# Generated by Django 4.0.3 on 2022-09-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezikr', '0006_challange_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
