# Generated by Django 4.0.3 on 2022-09-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezikr', '0008_task_time_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_count',
            field=models.IntegerField(default=0),
        ),
    ]
